// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4xwXIja21DyXZFunUm3sgUwp5VpCFCUU',
    appId: '1:937007958324:web:857e0e82d11e568c4b7d61',
    messagingSenderId: '937007958324',
    projectId: 'smart-collector-92361',
    authDomain: 'smart-collector-92361.firebaseapp.com',
    storageBucket: 'smart-collector-92361.appspot.com',
    measurementId: 'G-M3T5P6QLFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9-otodHBEmWe5vPTXtRlXEZays79oCSc',
    appId: '1:937007958324:android:8e3add4f9f07e8be4b7d61',
    messagingSenderId: '937007958324',
    projectId: 'smart-collector-92361',
    storageBucket: 'smart-collector-92361.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqUKaCCEtycmX_Jt6SgtGuizWsGoA3XKQ',
    appId: '1:937007958324:ios:d3243d7052e11d454b7d61',
    messagingSenderId: '937007958324',
    projectId: 'smart-collector-92361',
    storageBucket: 'smart-collector-92361.appspot.com',
    iosClientId: '937007958324-357dmcgatg2a812aba05btchm55lkk3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartCollector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqUKaCCEtycmX_Jt6SgtGuizWsGoA3XKQ',
    appId: '1:937007958324:ios:d3243d7052e11d454b7d61',
    messagingSenderId: '937007958324',
    projectId: 'smart-collector-92361',
    storageBucket: 'smart-collector-92361.appspot.com',
    iosClientId: '937007958324-357dmcgatg2a812aba05btchm55lkk3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartCollector',
  );
}
